language: r
cache: packages
# dist: xenial

os: 
  - linux
  # - osx

r_packages:
  - txtplot

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/nLTT
  - ropensci/beastier@develop
  - ropensci/tracerer@develop
  - ropensci/mauricer
  - ropensci/babette

before_install:
  - echo $TRAVIS_OS_NAME
  # No need to brew install mpfr on macOS
  # Error: mpfr 4.0.1 is already installed
  # To upgrade to 4.0.2, run `brew upgrade mpfr`
  # if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpfr; fi
  # Do install mpfr on Linux
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt install -qq libmpfr-dev; fi

before_script:
  - # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # Should build with and without BEAST2 installed
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e 'mauricer::install_beast2_pkg("NS")'
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz

after_success:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then travis_wait 120 Rscript run.R; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then Rscript -e "lintr::lint_package()"; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then travis_wait 20 Rscript -e "covr::codecov()"; fi
