language: r
dist: bionic
cache: packages

# ----------------+---------+-------------+
# Environment     | codecov | goodpractice|
# ----------------+---------+-------------+
# MacOS           | No      | No          |
# Linux r-devel   | Yes     | No          |
# Linux r-release | No      | Yes         |
# ----------------+---------+-------------+

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
    osx_image: xcode9.2

# It may be that this package uninstall BEAST2 and/or the packages
# before and after the tests.
# These variable allow to verify this
env:
  global:
    - beast2_installed_before=-1
    - beast2_installed_after=-1
    - beast2_ns_pkg_installed_before=-1
    - beast2_ns_pkg_installed_after=-1

r_github_packages:
  - ropensci/beautier
  - ropensci/beastier
  - ropensci/babette
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

before_install:
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --self; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install inconsolata; fi


before_script:
  - # echo "mcbette should build with and without BEAST2 installed"
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "beastier::is_beast2_installed()"
  - Rscript -e 'mauricer::install_beast2_pkg("NS")'
  - Rscript -e 'mauricer::is_beast2_ns_pkg_installed()'
  - beast2_installed_before=$(Rscript -e "beastier::is_beast2_installed()")
  - beast2_ns_pkg_installed_before=$(Rscript -e 'mauricer::is_beast2_ns_pkg_installed()')
  - echo $beast2_installed_before
  - echo $beast2_ns_pkg_installed_before

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz
  - beast2_installed_after=$(Rscript -e "beastier::is_beast2_installed()")
  - beast2_ns_pkg_installed_after=$(Rscript -e 'mauricer::is_beast2_ns_pkg_installed()')
  - echo $beast2_installed_after
  - echo $beast2_ns_pkg_installed_after
  - if [ "$beast2_installed_before" != "$beast2_installed_after" ]; then echo "ERROR! THEY DIFFER!"; exit 1; fi
  - if [ "$beast2_ns_pkg_installed_before" != "$beast2_ns_pkg_installed_after" ]; then echo "ERROR! THEY DIFFER!"; exit 1; fi

after_success:
  # Codecov
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 60 Rscript -e 'covr::codecov()'; fi
  # Goodpractice
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then travis_wait 60 Rscript -e 'goodpractice::gp()'; fi
  # Report
  - Rscript -e "beastier::is_beast2_installed()"
  - Rscript -e 'mauricer::is_beast2_ns_pkg_installed()'
  - Rscript -e 'remotes::install_github("richelbilderbeek/mcbette")'
  - Rscript -e 'mcbette::mcbette_report()'

after_failure:
  # Report
  - Rscript -e "beastier::is_beast2_installed()"
  - Rscript -e 'mauricer::is_beast2_ns_pkg_installed()'
  - Rscript -e 'remotes::install_github("richelbilderbeek/mcbette")'
  - Rscript -e 'mcbette::mcbette_report()'

