language: r
cache: packages

r_packages:
  - txtplot

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - ropensci/beastier
  - ropensci/beautier
  - ropensci/mauricer
  - ropensci/tracerer

before_install:
  - sudo apt install -qq libmpfr-dev

before_script:
  - sudo apt-get install -qq oracle-java8-installer
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e 'mauricer::mrc_install("NS")'
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'

after_success:
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'
  - travis_wait 120 Rscript run.R
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
