language: r
cache: packages

os: 
  - osx
  - linux

r_packages:
  - txtplot

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette

before_install:
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpfr; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt install -qq libmpfr-dev; fi

before_script:
  - # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e 'mauricer::install_beast2_pkg("NS")'
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'

script:
  - travis_wait 50 R CMD build .

after_success:
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'
  - travis_wait 120 Rscript run.R
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
