language: r
cache: packages

os: 
  - osx
  - linux

r_packages:
  - txtplot

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette

before_install:
  - sudo apt install -qq libmpfr-dev

before_script:
  - # sudo apt-get install -qq oracle-java8-installer
  - # sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e 'mauricer::install_beast2_pkg("NS")'
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'

after_success:
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'
  - travis_wait 120 Rscript run.R
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
