language: r
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - richelbilderbeek/beastier
  - richelbilderbeek/beautier
  - richelbilderbeek/mauricer
  - richelbilderbeek/tracerer

before_script:
  - sudo apt-get install -qq oracle-java8-installer
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e 'mauricer::mrc_install("NS")'

after_success:
  - Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'
  - travis_wait 120 Rscript run.R
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
